------------
-- C++
------------
--Remember to use asyncrun
--Command for running cmake
--Command for building i.e make
--Command for running
--Command for generating make config
--Command for clearing build files
